# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ml_engine_pb2 as ml__engine__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLEngineServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictMatch = channel.unary_unary(
                '/ml_engine.MLEngineService/PredictMatch',
                request_serializer=ml__engine__pb2.PredictMatchRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.PredictMatchResponse.FromString,
                _registered_method=True)
        self.PredictBatch = channel.unary_unary(
                '/ml_engine.MLEngineService/PredictBatch',
                request_serializer=ml__engine__pb2.PredictBatchRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.PredictBatchResponse.FromString,
                _registered_method=True)
        self.TrainModel = channel.unary_unary(
                '/ml_engine.MLEngineService/TrainModel',
                request_serializer=ml__engine__pb2.TrainModelRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.TrainModelResponse.FromString,
                _registered_method=True)
        self.GetModelStatus = channel.unary_unary(
                '/ml_engine.MLEngineService/GetModelStatus',
                request_serializer=ml__engine__pb2.GetModelStatusRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.GetModelStatusResponse.FromString,
                _registered_method=True)
        self.GenerateProjectEmbedding = channel.unary_unary(
                '/ml_engine.MLEngineService/GenerateProjectEmbedding',
                request_serializer=ml__engine__pb2.ProjectEmbeddingRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.GenerateStudentEmbedding = channel.unary_unary(
                '/ml_engine.MLEngineService/GenerateStudentEmbedding',
                request_serializer=ml__engine__pb2.StudentEmbeddingRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.GenerateSkillEmbedding = channel.unary_unary(
                '/ml_engine.MLEngineService/GenerateSkillEmbedding',
                request_serializer=ml__engine__pb2.SkillEmbeddingRequest.SerializeToString,
                response_deserializer=ml__engine__pb2.EmbeddingResponse.FromString,
                _registered_method=True)


class MLEngineServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PredictMatch(self, request, context):
        """Predicción técnica (Solo matemáticas e IA)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictBatch(self, request, context):
        """Predicción por lotes (Optimizado para rendimiento)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """Administración del motor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateProjectEmbedding(self, request, context):
        """Webhooks asíncronos para reconstrucción relacional
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateStudentEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSkillEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictMatch,
                    request_deserializer=ml__engine__pb2.PredictMatchRequest.FromString,
                    response_serializer=ml__engine__pb2.PredictMatchResponse.SerializeToString,
            ),
            'PredictBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictBatch,
                    request_deserializer=ml__engine__pb2.PredictBatchRequest.FromString,
                    response_serializer=ml__engine__pb2.PredictBatchResponse.SerializeToString,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=ml__engine__pb2.TrainModelRequest.FromString,
                    response_serializer=ml__engine__pb2.TrainModelResponse.SerializeToString,
            ),
            'GetModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStatus,
                    request_deserializer=ml__engine__pb2.GetModelStatusRequest.FromString,
                    response_serializer=ml__engine__pb2.GetModelStatusResponse.SerializeToString,
            ),
            'GenerateProjectEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateProjectEmbedding,
                    request_deserializer=ml__engine__pb2.ProjectEmbeddingRequest.FromString,
                    response_serializer=ml__engine__pb2.EmbeddingResponse.SerializeToString,
            ),
            'GenerateStudentEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateStudentEmbedding,
                    request_deserializer=ml__engine__pb2.StudentEmbeddingRequest.FromString,
                    response_serializer=ml__engine__pb2.EmbeddingResponse.SerializeToString,
            ),
            'GenerateSkillEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSkillEmbedding,
                    request_deserializer=ml__engine__pb2.SkillEmbeddingRequest.FromString,
                    response_serializer=ml__engine__pb2.EmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml_engine.MLEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ml_engine.MLEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLEngineService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_engine.MLEngineService/PredictMatch',
            ml__engine__pb2.PredictMatchRequest.SerializeToString,
            ml__engine__pb2.PredictMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_engine.MLEngineService/PredictBatch',
            ml__engine__pb2.PredictBatchRequest.SerializeToString,
            ml__engine__pb2.PredictBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_engine.MLEngineService/TrainModel',
            ml__engine__pb2.TrainModelRequest.SerializeToString,
            ml__engine__pb2.TrainModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_engine.MLEngineService/GetModelStatus',
            ml__engine__pb2.GetModelStatusRequest.SerializeToString,
            ml__engine__pb2.GetModelStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateProjectEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_engine.MLEngineService/GenerateProjectEmbedding',
            ml__engine__pb2.ProjectEmbeddingRequest.SerializeToString,
            ml__engine__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateStudentEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_engine.MLEngineService/GenerateStudentEmbedding',
            ml__engine__pb2.StudentEmbeddingRequest.SerializeToString,
            ml__engine__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateSkillEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_engine.MLEngineService/GenerateSkillEmbedding',
            ml__engine__pb2.SkillEmbeddingRequest.SerializeToString,
            ml__engine__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
